spring:
    application:
        name: OrderService
    datasource:
        driver-class-name: org.postgresql.Driver
        username: ${TEST_DB_USERNAME}
        password: ${TEST_DB_PASSWORD}
        url: jdbc:postgresql://localhost:5435/order_service
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: false
    flyway:
      out-of-order: false
      default-schema: order_service
      locations: classpath:db/migration
      enabled: true